[window]

padding  = {x=10,y=10} 

opacity = 0.5

blur = false

[font]
size = 13

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
# BEGIN WAL
[colors.primary]
background = '#090a0c'
foreground = '#9eaabc'

[colors.cursor]
text   = '#090a0c' # Apply background color to color of text inside cursor
cursor = '#9eaabc' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#090a0c' # Same as above
cursor  = '#9eaabc'

[colors.search.matches]
foreground = '#090a0c' # Same as above
background = '#9eaabc' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#6e7683'
background = '#9eaabc'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#090a0c'
red     = '#384358'
green   = '#3A4E6A'
yellow  = '#4C4F61'
blue    = '#3D5E85'
magenta = '#3F6187'
cyan    = '#4F6689'
white   = '#9eaabc'

[colors.bright]
black   = '#6e7683'
red     = '#384358'
green   = '#3A4E6A'
yellow  = '#4C4F61'
blue    = '#3D5E85'
magenta = '#3F6187'
cyan    = '#4F6689'
white   = '#9eaabc'
# END WAL
