[window]

padding  = {x=10,y=10} 

opacity = 0.5

blur = false

[font]
size = 13

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
# BEGIN WAL
[colors.primary]
background = '#06011A'
foreground = '#e2c9e8'

[colors.cursor]
text   = '#06011A' # Apply background color to color of text inside cursor
cursor = '#e2c9e8' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#06011A' # Same as above
cursor  = '#e2c9e8'

[colors.search.matches]
foreground = '#06011A' # Same as above
background = '#e2c9e8' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#9e8ca2'
background = '#e2c9e8'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#06011A'
red     = '#A761BB'
green   = '#6289BB'
yellow  = '#2E95D7'
blue    = '#5696D7'
magenta = '#7193D5'
cyan    = '#9C9EDE'
white   = '#e2c9e8'

[colors.bright]
black   = '#9e8ca2'
red     = '#A761BB'
green   = '#6289BB'
yellow  = '#2E95D7'
blue    = '#5696D7'
magenta = '#7193D5'
cyan    = '#9C9EDE'
white   = '#e2c9e8'
# END WAL
